[RND-426] - Unable to create StudentSchoolAssociation with GraduationPlan reference
Ed-Fi-Exchange-OSS/Meadowlark pull request #129
Opened 2022-10-26 18:36 UTC by stevenarnold-ed-fi

also updated version of test reporter

2022-10-28 00:23 UTC, bradbanister reviewed
This looks good. Just waiting on a test.

2022-10-31 19:55 UTC, andonyns approved these changes

2022-10-31 20:00 UTC, andonyns requested changes

2022-10-31 20:00 UTC, andonyns commented on Meadowlark-js/packages/meadowlark-core/test/extraction/DocumentReferenceExtractor.test.ts
> +  it('should have references and then schoolYear reference should respect the role name', () => {
```suggestion
  it('should have references and schoolYear reference should respect the role name', () => {
```

2022-10-31 20:00 UTC, andonyns commented on Meadowlark-js/packages/meadowlark-core/test/extraction/DocumentReferenceExtractor.test.ts
> +describe('when extracting with a school year in a reference document', () => {
```suggestion
describe('when extracting with school year in a reference document', () => {
```

I think it's better to have a similar name to the other test for easier location

2022-10-31 20:11 UTC, merged