[BIA-560] Postgres: Deleting resource is not deleting references and alias
Ed-Fi-Exchange-OSS/Meadowlark pull request #246
Opened 2023-05-24 00:28 UTC by jleiva-gap

Update delete and update modules.
Update test to validate if aliases and references are deleted when a document is deleted. Update update module to use an old meadowlarkId to filter aliases and references, because, if it change, this query will return empty. Add validation to use enable or disable allow Identity Updates

## Description

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I have signed all of the commits on this PR.
- [ ] I have agreed to the Ed-Fi Individual Contributors' License
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-05-24 22:10 UTC, andonyns approved these changes

2023-05-25 15:13 UTC, bradbanister commented on Meadowlark-js/backends/meadowlark-postgresql-backend/src/repository/Delete.ts
> +      if (meadowlarkId.length === 0) {
why not `meadowlarkId === ''`? This looks like an array test.

2023-05-25 15:20 UTC, bradbanister commented on Meadowlark-js/backends/meadowlark-postgresql-backend/src/repository/SqlHelper.ts
> +}
This looks like test code. Why put it here?

2023-05-25 15:25 UTC, bradbanister requested changes
A few minor changes

2023-05-25 16:05 UTC, jleiva-gap commented on Meadowlark-js/backends/meadowlark-postgresql-backend/src/repository/Update.ts
> +    const existingMeadowlardId: MeadowlarkId = recordExistsResult.rows[0].document_id;
2. Line 53 returns a failure if recordExistsResult doesn't have rows.

2023-05-25 16:54 UTC, merged