[METAED-1492] cache all compiled JSON Schema validation functions
Ed-Fi-Exchange-OSS/Meadowlark pull request #285
Opened 2023-08-10 21:46 UTC by bradbanister

2023-08-10 22:34 UTC, andonyns commented on Meadowlark-js/tests/profiling/package-lock.json
We don't have a package-lock.json file in any of the other projects with package.json because lerna handles it in the main package-lock.json. Is this required for this project?

2023-08-11 13:58 UTC, bradbanister commented on Meadowlark-js/tests/profiling/package-lock.json
Removed this as part of converting to a Jest threshhold test

2023-08-11 16:19 UTC, andonyns commented on Meadowlark-js/services/meadowlark-fastify/src/index.ts
> +  // new ClusterService(serviceFactory).run();
Was this commented for testing or should the line be removed?

2023-08-11 16:27 UTC, andonyns commented on Meadowlark-js/tests/profiling/Schools.test.ts
> +    expect(result.latency.p50).toBeLessThan(500);
Awesome!

2023-08-11 19:58 UTC, andonyns requested changes

2023-08-11 19:58 UTC, andonyns commented on Meadowlark-js/services/meadowlark-fastify/package.json
> +    "clinic:flame": "FASTIFY_NUM_THREADS=1 clinic flame -- node dist/index.js",
This is missing the cross-env to set the environment variable.

Given that the clinic dependency is the main package.json shouldn't these scripts be also on the main package.json file?

2023-08-11 20:08 UTC, andonyns commented on Meadowlark-js/tests/profiling/readme.md
> +   - `npx jest tests/profiling/Schools.test.ts` for an automated test that passes if the median latency is below a threshhold value.
small typo in doc: threshold

2023-08-11 20:32 UTC, andonyns approved these changes

2023-08-11 20:32 UTC, merged