client_id for claim ownership
Ed-Fi-Exchange-OSS/Meadowlark pull request #83
Opened 2022-08-16 17:45 UTC by stevenarnold-ed-fi

Added client_id to token
updated Meadowlark to look for clientId rather than clientName
updated OAuth to return client_id in token
updated tokens for system and http tests to have client_id

2022-08-16 17:46 UTC, stevenarnold-ed-fi commented on Meadowlark-js/backends/meadowlark-mongodb-backend/test/integration/OwnershipSecurity.test.ts
> +  const clientId = 'ThisClient';
For integration tests, I kept the old client name for the clientId, for system and http tests, I added client_id to the token and base64 encoded the clientName to get a clientId

2022-08-16 17:48 UTC, stevenarnold-ed-fi commented on Meadowlark-js/packages/meadowlark-core/src/security/JwtAction.ts
> +export function createToken(clientId: string, vendor: string, role: string): Jwt {
For hardcoded credentials, used the client key as the client id

2022-08-17 14:28 UTC, bradbanister requested changes
On several of the local.token.http tests I get 500 errors with `Cannot read properties of undefined (reading 'client_id')`

2022-08-17 19:18 UTC, bradbanister approved these changes
Looks good

2022-08-17 19:18 UTC, merged