RND-326 - Adding total count from open search
Ed-Fi-Exchange-OSS/Meadowlark pull request #98
Opened 2022-09-02 20:31 UTC by stevenarnold-ed-fi

2022-09-02 20:34 UTC, stevenarnold-ed-fi commented on Meadowlark-js/packages/meadowlark-core/src/handler/Query.ts
> +const TOTAL_COUNT_HEADER_NAME: string = 'total-count';
Added - so that it matched most existing headers. totalCount would become 'totalcount' in the headers, which looks weird to me.

2022-09-02 21:04 UTC, stephenfuqua commented on Meadowlark-js/packages/meadowlark-core/src/handler/Query.ts
> +  };
There's one "problem" with this: the ODS/API only reports the total-count header if you use the query string `totalCount=true`. We're reporting in all cases. That said, it doesn't really matter. We didn't make any extra effort to get this information from OpenSearch, so let's just include it. So I'm fine with this.

2022-09-02 21:07 UTC, stephenfuqua requested changes
Code looks good. Would like to see unit test coverage too: both `Query` and `QueryOpensearch` have tests files already, so should be easy to extend the coverage.

2022-09-06 16:00 UTC, stephenfuqua approved these changes

2022-09-06 16:01 UTC, merged